export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_DISCOVERY = 'GET_DISCOVERY';
export const GET_SESSION = 'GET_SESSION';
export const SET_USERNAME = 'SET_USERNAME';
export const SET_PASSWORD = 'SET_PASSWORD';