import io.nzbee.domain.bag.Bag;
import io.nzbee.domain.bag.BagItem;
import io.nzbee.domain.product.Product;
import java.util.List;

dialect "mvel"

global List<Product> outOfStockProducts;

function String pendingItemKey(BagItem bagItem) { 
	return bagItem.getBag().getCustomer().getCustomerID() + "-"+ bagItem.getProduct().getProductDesc();
}
//Is it out of stock?
rule "Is Out-Of Stock"
when
$bagItem : BagItem(!bagItemStatus.equals("PRO01") && !product.isInStock())
then
System.out.println("\nIs Out-Of Stock Rule");
System.out.println("************************************");
String error = "Can't process as " +  $bagItem.getProduct().getProductDesc() + " is Out-Of-Stock" ;
System.out.println(error);
$bagItem.setErrors(true);
$bagItem.setError(error);
$bagItem.getBag().logItemError(pendingItemKey($bagItem), $bagItem);
outOfStockProducts.add($bagItem.getProduct());
end