spring:
  devtools:
    restart:
      enabled: false
      exclude: data/downloads/**,target/**
      
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-request-size: 215MB
      max-file-size: 200MB
      
  profiles:
    active: dev
  
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        driver_class: org.postgresql.Driver    
    
logging:
  level: 
    org:
      springframework:
        web: ERROR
      hibernate: WARN
        
    io:
      nzbee: DEBUG
      
      
file:
  upload-dir: data/uploads/
  download-dir: data/downloads/
  product-master-file: product_master.csv

server:
  port: 8090
  ssl:
    key-store-type: PKCS12
    key-store: classpath:mochi.p12
    key-store-password: password
    key-alias: mochi

app:
  globals:
    baseURL: https://localhost:8080
    localeENGB: en-GB
    localeZHHK: zh-HK
    currencyHKD: HKD
    currencyUSD: USD
    retailPriceCode: RET01
    markdownPriceCode: MKD01
    unknownProductDesc: Not Applicable
    unknownProductImage: unknown.jpg
    activeSKUCode: ACT01
    primaryRootCategoryCode: PRM01
    defaultPage: 0
    defaultPageSize: 10
    productTypeCodeFood: FOO01