package io.nzbee.util.inventory;

public class InventoryMasterSchema {

	
	private String INVENTORY_LOCATION_CODE;
		
	private String INVENTORY_PRODUCT_UPC;
	
	private double INVENTORY_QUANTITY;
	
	private double INVENTORY_PRICE;
	
	private String INVENTORY_CURRENCY_CODE;
	
	private String INVENTORY_TYPE_CODE;
	
	private String INVENTORY_SUPPLIER_ID;
	
	private String INVENTORY_TRANSACTION_DATE;

	public String get_INVENTORY_LOCATION_CODE() {
		return INVENTORY_LOCATION_CODE;
	}

	public void set_INVENTORY_LOCATION_CODE(String iNVENTORY_LOCATION_CODE) {
		INVENTORY_LOCATION_CODE = iNVENTORY_LOCATION_CODE;
	}

	public String get_INVENTORY_PRODUCT_UPC() {
		return INVENTORY_PRODUCT_UPC;
	}

	public void set_INVENTORY_PRODUCT_UPC(String iNVENTORY_PRODUCT_UPC) {
		INVENTORY_PRODUCT_UPC = iNVENTORY_PRODUCT_UPC;
	}

	public double get_INVENTORY_QUANTITY() {
		return INVENTORY_QUANTITY;
	}

	public void set_INVENTORY_QUANTITY(double iNVENTORY_QUANTITY) {
		INVENTORY_QUANTITY = iNVENTORY_QUANTITY;
	}

	public double get_INVENTORY_PRICE() {
		return INVENTORY_PRICE;
	}

	public void set_INVENTORY_PRICE(double iNVENTORY_PRICE) {
		INVENTORY_PRICE = iNVENTORY_PRICE;
	}

	public String get_INVENTORY_CURRENCY_CODE() {
		return INVENTORY_CURRENCY_CODE;
	}

	public void set_INVENTORY_CURRENCY_CODE(String iNVENTORY_CURRENCY_CODE) {
		INVENTORY_CURRENCY_CODE = iNVENTORY_CURRENCY_CODE;
	}

	public String get_INVENTORY_TYPE_CODE() {
		return INVENTORY_TYPE_CODE;
	}

	public void set_INVENTORY_TYPE_CODE(String iNVENTORY_TYPE_CODE) {
		INVENTORY_TYPE_CODE = iNVENTORY_TYPE_CODE;
	}

	public String get_INVENTORY_SUPPLIER_ID() {
		return INVENTORY_SUPPLIER_ID;
	}

	public void set_INVENTORY_SUPPLIER_ID(String iNVENTORY_SUPPLIER_ID) {
		INVENTORY_SUPPLIER_ID = iNVENTORY_SUPPLIER_ID;
	}

	public String get_INVENTORY_TRANSACTION_DATE() {
		return INVENTORY_TRANSACTION_DATE;
	}

	public void set_INVENTORY_TRANSACTION_DATE(String iNVENTORY_TRANSACTION_DATE) {
		INVENTORY_TRANSACTION_DATE = iNVENTORY_TRANSACTION_DATE;
	}
	
	
}
